apiVersion: v1
kind: Namespace
metadata:
  name: even
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-even
  namespace: even
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-even
  template:
    metadata:
      labels:
        app: api-even
    spec:
      containers:
        - name: api-even
          image: ghcr.io/chawil/api-even:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-even
  namespace: even
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: api-even
